# Developer convenience targets. CI is the source of truth — see
# .github/workflows/validate.yml for the full check matrix. Targets
# here mirror specific CI steps so contributors can reproduce them
# locally without copying shell out of the workflow.

SHELL := bash
.SHELLFLAGS := -eu -o pipefail -c

# Where `go install` puts binaries. Picks up $GOBIN if set, falls
# back to $GOPATH/bin, falls back to ~/go/bin.
GOBIN ?= $(shell go env GOBIN)
ifeq ($(GOBIN),)
GOBIN := $(shell go env GOPATH)/bin
endif

# Pinned versions. Bump deliberately; see CHANGELOG.
TOML_TEST_VERSION         := v1.6.0
# This decoder is shipped by the same BurntSushi/toml module the Go
# validator (tools/dagtoml-validate-go) depends on. Conformance of
# this decoder is therefore evidence about the parser the Go
# validator actually uses at runtime. Pinned to v1.6.0 to MATCH
# tools/dagtoml-validate-go/go.mod — v1.6.0 enables TOML 1.1 by default,
# so the conformance evidence is now generated by the same 1.1 parser
# the Go validator runs (closing the pre-migration gap where the decoder
# was v1.4.0/1.0-era while the validator already linked 1.1).
TOML_TEST_DECODER_VERSION := v1.6.0

# The 13 invalid-test names BurntSushi/toml v1.6.0 fails to reject under
# the TOML 1.1 corpus (`-toml 1.1.0`). All are edge cases around
# dotted-key / inline-table redefinition; BurntSushi is permissive on
# them independent of TOML version (the same 13 failed under v1.4.0 on
# the 1.0 corpus — bumping the decoder v1.4.0 -> v1.6.0 and flipping the
# corpus 1.0 -> 1.1.0 left this set unchanged). This is a baseline of
# *currently-known-tolerated-permissiveness*, NOT a green light — each
# entry should be revisited when bumping TOML_TEST_DECODER_VERSION. If a
# bump newly passes one of these, remove it. If a bump newly fails
# something not listed, treat that as a regression and fix the bump
# rather than extend the list.
#
# Space-separated; the recipe turns each into a repeated `-skip`
# flag via $(addprefix). Don't comma-join: make line-continuation
# would inject spaces and toml-test would parse only the first.
TOML_CONFORMANCE_SKIPS := \
  invalid/array/extend-defined-aot \
  invalid/inline-table/duplicate-key-3 \
  invalid/inline-table/overwrite-02 \
  invalid/inline-table/overwrite-08 \
  invalid/spec/inline-table-2-0 \
  invalid/spec/table-9-1 \
  invalid/table/append-to-array-with-dotted-keys \
  invalid/table/append-with-dotted-keys-1 \
  invalid/table/append-with-dotted-keys-2 \
  invalid/table/duplicate-key-dotted-table \
  invalid/table/duplicate-key-dotted-table2 \
  invalid/table/redefine-2 \
  invalid/table/redefine-3

# Path to the in-repo Rust decoder shim. Built by
# `toml-conformance-rs` from tools/toml-test-decode-rs/. The shim
# uses the same `toml` 1.1 crate that tools/dagtoml-validate-rs
# depends on, so a green run here is evidence about the parser the
# Rust validator actually uses at runtime — the symmetric half of
# the BurntSushi/toml conformance check above.
RS_DECODER_BIN := tools/toml-test-decode-rs/target/release/toml-test-decode-rs

.PHONY: help toml-conformance toml-conformance-install toml-conformance-rs toml-conformance-all dagtoml-conformance

help: ## Show available targets.
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[1m%-32s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

toml-conformance-install: ## Install pinned toml-test + BurntSushi decoder under $GOBIN.
	GOBIN=$(GOBIN) go install github.com/toml-lang/toml-test/cmd/toml-test@$(TOML_TEST_VERSION)
	GOBIN=$(GOBIN) go install github.com/BurntSushi/toml/cmd/toml-test-decoder@$(TOML_TEST_DECODER_VERSION)

toml-conformance: ## Run TOML 1.1 spec-conformance suite against the BurntSushi parser used by tools/dagtoml-validate-go.
	@test -x "$(GOBIN)/toml-test"          || { echo "missing $(GOBIN)/toml-test — run: make toml-conformance-install"; exit 2; }
	@test -x "$(GOBIN)/toml-test-decoder"  || { echo "missing $(GOBIN)/toml-test-decoder — run: make toml-conformance-install"; exit 2; }
	$(GOBIN)/toml-test -toml 1.1.0 $(addprefix -skip ,$(TOML_CONFORMANCE_SKIPS)) $(GOBIN)/toml-test-decoder

toml-conformance-rs: ## Run TOML 1.1 spec-conformance suite against the `toml` crate used by tools/dagtoml-validate-rs.
	@test -x "$(GOBIN)/toml-test" || { echo "missing $(GOBIN)/toml-test — run: make toml-conformance-install"; exit 2; }
	cargo build --release --locked --manifest-path tools/toml-test-decode-rs/Cargo.toml \
	  || cargo build --release --manifest-path tools/toml-test-decode-rs/Cargo.toml
	# Empirical: the Rust `toml` 1.1 crate passes the full TOML 1.1 suite
	# (189/189 valid + 362/362 invalid under `-toml 1.1.0`, zero skips
	# needed) — strictly stronger than the BurntSushi decoder, which still
	# tolerates the 13 dotted-key/inline-table cases skipped above. No
	# permissiveness-baseline list to maintain on the Rust side. If a future
	# crate bump starts failing tests, add a TOML_CONFORMANCE_RS_SKIPS
	# variable mirroring TOML_CONFORMANCE_SKIPS above and route it through
	# the same `-skip` flag expansion. Empty for now is intentional.
	$(GOBIN)/toml-test -toml 1.1.0 "$(abspath $(RS_DECODER_BIN))"

toml-conformance-all: toml-conformance toml-conformance-rs ## Run both Go-parser and Rust-parser conformance suites.

dagtoml-conformance: ## Run the cross-implementation DAG-TOML semantic conformance corpus (conformance/).
	cargo build --release --locked --manifest-path tools/dagtoml-validate-rs/Cargo.toml \
	  || cargo build --release --manifest-path tools/dagtoml-validate-rs/Cargo.toml
	cd tools/dagtoml-validate-go && go build -o "$(CURDIR)/dagtoml-validate-go.conformance" .
	python3 conformance/runner.py \
	  --rs tools/dagtoml-validate-rs/target/release/dagtoml-validate-rs \
	  --go "$(CURDIR)/dagtoml-validate-go.conformance"
	rm -f "$(CURDIR)/dagtoml-validate-go.conformance"
