-- DAG-TOML reference SQLite seed (non-normative).
--
-- Sibling of reference/database/postgres/seed.sql. Same registry data,
-- adapted to SQLite syntax:
--   * No CREATE SCHEMA — table names carry the `dagtoml_` prefix.
--   * Arrays are JSON strings (text[] in PG → json_array(...) here).
--   * Booleans are 0/1 integers (no native bool in SQLite).
--
-- Counts (CI-gated by validators/check_attribute_values.py; drift fails):
--   23 template kinds       (6 core + 9 agent-assurance + 3 disclosure + 1 cost + 3 com.verivus.runtime + 1 meta)
--   27 entity kinds         (17 core + 6 agent-assurance + 3 disclosure + 1 cost)
--   31 relation rows        (26 core + 5 contract-namespaced variants)
--   50 attribute vocabs     (12 core + 27 agent-assurance + 4 disclosure + 3 cost + 4 com.verivus.runtime)
--  216 attribute_value_allowed rows (complete declared catalog, including
--                                    native-backed tokens and runtime operands)

PRAGMA foreign_keys = ON;

-- ============================================================
-- kind_descriptor (23 rows; +1 cost-record, +3 com.verivus.runtime)
-- ============================================================
INSERT INTO dagtoml_kind_descriptor (template_kind, layer, descriptor_path, requires_profile) VALUES
    ('kind-descriptor',           'core', 'spec.md',                                                       NULL),
    ('implementation-dag',        'core', 'core/implementation-dag-kind.toml',                             NULL),
    ('traceability',              'core', 'core/traceability-kind.toml',                                   NULL),
    ('readiness-gate',            'core', 'core/readiness-gate-kind.toml',                                 NULL),
    ('contract-declaration',      'core', 'core/contract-declaration-kind.toml',                           NULL),
    ('evidence-matrix',           'core', 'core/evidence-matrix-kind.toml',                                NULL),
    ('profile-descriptor',        'core', 'core/profile-descriptor-kind.toml',                             NULL),
    ('spec-contract',             'profile:agent-assurance', 'profiles/agent-assurance/spec-contract-kind.toml',             'agent-assurance'),
    ('threat-model',              'profile:agent-assurance', 'profiles/agent-assurance/threat-model-kind.toml',              'agent-assurance'),
    ('smoke-validation',          'profile:agent-assurance', 'profiles/agent-assurance/smoke-validation-kind.toml',          'agent-assurance'),
    ('rollback-plan',             'profile:agent-assurance', 'profiles/agent-assurance/rollback-plan-kind.toml',             'agent-assurance'),
    ('adapter-contract',          'profile:agent-assurance', 'profiles/agent-assurance/adapter-contract-kind.toml',          'agent-assurance'),
    ('adapter-registry-binding',  'profile:agent-assurance', 'profiles/agent-assurance/adapter-registry-binding-kind.toml',  'agent-assurance'),
    ('assertion-bundle',          'profile:agent-assurance', 'profiles/agent-assurance/assertion-bundle-kind.toml',          'agent-assurance'),
    ('assertion-log-record',      'profile:agent-assurance', 'profiles/agent-assurance/assertion-log-record-kind.toml',      'agent-assurance'),
    ('gate-decision',             'profile:agent-assurance', 'profiles/agent-assurance/gate-decision-kind.toml',             'agent-assurance'),
    ('disclosure-attestation',    'profile:disclosure',      'profiles/disclosure/disclosure-attestation-kind.toml',         'disclosure'),
    ('redaction-manifest',        'profile:disclosure',      'profiles/disclosure/redaction-manifest-kind.toml',             'disclosure'),
    ('selective-disclosure-proof','profile:disclosure',      'profiles/disclosure/selective-disclosure-proof-kind.toml',     'disclosure'),
    ('cost-record',               'profile:cost',            'profiles/cost/cost-record-kind.toml',                          'cost'),
    ('api-snapshot',              'profile:com.verivus.runtime', 'profiles/com.verivus.runtime/api-snapshot-kind.toml',       'com.verivus.runtime'),
    ('state-mutation',            'profile:com.verivus.runtime', 'profiles/com.verivus.runtime/state-mutation-kind.toml',     'com.verivus.runtime'),
    ('mutation-claim',            'profile:com.verivus.runtime', 'profiles/com.verivus.runtime/mutation-claim-kind.toml',     'com.verivus.runtime');

-- ============================================================
-- entity_kind_descriptor (27 rows; +1 cost = COST)
-- ============================================================
INSERT INTO dagtoml_entity_kind_descriptor (entity_kind, id_prefix_pattern, layer, defining_kind, ijb_primitive, ijb_class, description) VALUES
    ('intent',           'INT',           'core', 'traceability',         'thing', 'structural', 'User/business intent; top of trace.'),
    ('feature',          'FEAT',          'core', 'traceability',         'thing', 'structural', 'User-visible capability.'),
    ('requirement',      'REQ',           'core', 'traceability',         'thing', 'structural', 'Normative, testable requirement.'),
    ('regulation',       'REG',           'core', 'traceability',         'thing', 'structural', 'Legal/policy/regulatory obligation.'),
    ('decision',         'DEC',           'core', 'traceability',         'thing', 'structural', 'Design or policy decision.'),
    ('implementation',   'IMP',           'core', 'traceability',         'thing', 'structural', 'Implementation work package.'),
    ('code',             'CODE',          'core', 'traceability',         'thing', 'structural', 'Concrete code artifact.'),
    ('test',             'TEST',          'core', 'traceability',         'thing', 'structural', 'Verification artifact.'),
    ('output',           'OUT',           'core', 'traceability',         'thing', 'structural', 'User-visible output or deliverable.'),
    ('unit',             'U\d+[a-z]?',    'core', 'implementation-dag',   'thing', 'structural', 'DAG unit (regex-keyed).'),
    ('artifact',         'ART',           'core', 'implementation-dag',   'thing', 'structural', 'Internal artifact flowing between DAG units.'),
    ('artifact_class',   'A\d+',          'core', 'readiness-gate',       'thing', 'structural', 'Review artifact class.'),
    ('gate',             'G\d+',          'core', 'readiness-gate',       'thing', 'structural', 'Readiness gate keyed to artifact class.'),
    ('contract',         'C\d+',          'core', 'contract-declaration', 'thing', 'structural', 'Declared contract.'),
    ('claim',            'E\d+',          'core', 'evidence-matrix',      'thing', 'structural', 'Strong claim.'),
    ('evidence',         'EV\d+',         'core', 'evidence-matrix',      'thing', 'structural', 'Proof artifact.'),
    ('matrix',           'M\d+',          'core', 'evidence-matrix',      'thing', 'structural', 'Claim↔evidence linkage.'),
    ('guarantee',        'GUAR',          'profile:agent-assurance', 'spec-contract',  'thing', 'structural', 'Measurable guarantee.'),
    ('invariant',        'INV',           'profile:agent-assurance', 'spec-contract',  'thing', 'structural', 'Invariant the implementation MUST not violate.'),
    ('non_goal',         'NG',            'profile:agent-assurance', 'spec-contract',  'thing', 'structural', 'Explicit non-goal of the change.'),
    ('threat',           'THREAT',        'profile:agent-assurance', 'threat-model',   'thing', 'structural', 'Identified threat to the change/system.'),
    ('smoke_check',      'SMOKE',         'profile:agent-assurance', 'smoke-validation','thing', 'structural', 'Smoke-validation check entry.'),
    ('rollback_trigger', 'TRIG',          'profile:agent-assurance', 'rollback-plan',  'thing', 'structural', 'Pre-declared rollback trigger condition.'),
    -- Profile: disclosure (3)
    ('disclosure_attestation',     'DISC', 'profile:disclosure', 'disclosure-attestation',     'thing', 'structural', 'Signed posture statement that a named subject was disclosed at a given posture.'),
    ('redaction',                  'RED',  'profile:disclosure', 'redaction-manifest',         'thing', 'structural', 'A byte-range or field-path inside a source artifact that was removed before publication.'),
    ('selective_disclosure_proof', 'SDP',  'profile:disclosure', 'selective-disclosure-proof', 'thing', 'structural', 'A commitment a recipient can verify to confirm the publisher knew the omitted content.'),
    ('cost_record',                'COST', 'profile:cost',       'cost-record',                'thing', 'structural', 'Declared cost of one costed action (Stream G Cost-Witnessed Decision).');

-- ============================================================
-- relation_descriptor (31 rows; +1 vs v1: SPEC §12 `cites_upstream`)
-- ============================================================
INSERT INTO dagtoml_relation_descriptor (predicate, domain, range, inverse_of, cardinality, is_acyclic, target_freeform, ijb_primitive, ijb_class, layer) VALUES
    ('derived_from',           json_array('intent'),                       json_array('intent'),                                       NULL,            NULL, 0, 0, 'path', 'structural', 'core'),
    ('realized_by',            json_array('intent'),                       json_array('feature','requirement'),                        'realizes',      NULL, 0, 0, 'path', 'structural', 'core'),
    ('realizes',               json_array('feature','code','output'),      json_array('intent','implementation','requirement','feature'), 'realized_by', NULL, 0, 0, 'path', 'structural', 'core'),
    ('constrained_by',         json_array('feature'),                      json_array('requirement','regulation'),                     'constrains',    NULL, 0, 0, 'path', 'structural', 'core'),
    ('implemented_by',         json_array('feature'),                      json_array('implementation'),                               'implements',    NULL, 0, 0, 'path', 'structural', 'core'),
    ('produces',               json_array('feature','unit'),               json_array('output','artifact'),                            NULL,            NULL, 0, 0, 'path', 'structural', 'core'),
    ('constrains',             json_array('requirement','regulation'),     json_array('feature','implementation','requirement'),       'constrained_by',NULL, 0, 0, 'path', 'structural', 'core'),
    ('verified_by',            json_array('requirement','regulation'),     json_array('test'),                                         'verifies',      NULL, 0, 0, 'path', 'structural', 'core'),
    ('addresses',              json_array('decision'),                     json_array('requirement','regulation'),                     NULL,            NULL, 0, 0, 'path', 'structural', 'core'),
    ('shapes',                 json_array('decision'),                     json_array('implementation','code'),                        NULL,            NULL, 0, 0, 'path', 'structural', 'core'),
    ('supersedes',             json_array('decision'),                     json_array('decision'),                                     NULL,            NULL, 1, 0, 'path', 'structural', 'core'),
    ('implements',             json_array('implementation'),               json_array('feature','requirement'),                        'implemented_by',NULL, 0, 0, 'path', 'structural', 'core'),
    ('guided_by',              json_array('implementation'),               json_array('decision'),                                     NULL,            NULL, 0, 0, 'path', 'structural', 'core'),
    ('code',                   json_array('implementation'),               json_array('code'),                                         NULL,            NULL, 0, 0, 'path', 'structural', 'core'),
    ('tests',                  json_array('implementation'),               json_array('test'),                                         NULL,            NULL, 0, 0, 'path', 'structural', 'core'),
    ('downstream_outputs',     json_array('implementation'),               json_array('output'),                                       NULL,            NULL, 0, 0, 'path', 'structural', 'core'),
    ('verifies',               json_array('test'),                         json_array('requirement','regulation'),                     'verified_by',   NULL, 0, 0, 'path', 'structural', 'core'),
    ('depends_on',             json_array('unit'),                         json_array('unit'),                                         'blocks',        NULL, 1, 0, 'path', 'structural', 'core'),
    ('blocks',                 json_array('unit'),                         json_array('unit'),                                         'depends_on',    NULL, 1, 0, 'path', 'structural', 'core'),
    ('consumes',               json_array('unit'),                         json_array('artifact'),                                     NULL,            NULL, 0, 0, 'path', 'structural', 'core'),
    ('artifact_class',         json_array('gate'),                         json_array('artifact_class'),                               NULL,            1,    0, 0, 'path', 'structural', 'core'),
    ('contract:depends_on',    json_array('contract'),                     json_array('contract'),                                     NULL,            NULL, 1, 0, 'path', 'structural', 'core'),
    ('contract:supersedes',    json_array('contract'),                     json_array('contract'),                                     NULL,            NULL, 1, 0, 'path', 'structural', 'core'),
    ('related_to',             json_array('contract'),                     json_array('contract'),                                     NULL,            NULL, 0, 0, 'path', 'structural', 'core'),
    ('applies_to',             json_array('contract'),                     json_array(),                                               NULL,            NULL, 0, 1, 'path', 'structural', 'core'),
    ('contract:verified_by',   json_array('contract'),                     json_array(),                                               NULL,            NULL, 0, 1, 'path', 'structural', 'core'),
    ('claim',                  json_array('matrix'),                       json_array('claim'),                                        NULL,            1,    0, 0, 'path', 'structural', 'core'),
    ('claim_id',               json_array('matrix'),                       json_array('claim'),                                        NULL,            1,    0, 0, 'path', 'structural', 'core'),
    ('evidence',               json_array('matrix'),                       json_array('evidence'),                                     NULL,            1,    0, 0, 'path', 'structural', 'core'),
    ('evidence_id',            json_array('matrix'),                       json_array('evidence'),                                     NULL,            1,    0, 0, 'path', 'structural', 'core'),
    -- Closure-root marker (SPEC §12) — applies to every conforming kind.
    ('cites_upstream',         json_array(),                               json_array(),                                               NULL,            NULL, 1, 1, 'path', 'structural', 'core');

-- ============================================================
-- attribute_vocabulary (50 rows; matches postgres/seed.sql vocab set; includes agent-assurance subject_class/provider_id/model_family_id for gate-decision INV06)
-- backing_check_constraint is an informational column/constraint hint.
-- NULL means no backing hint, including closed runtime-operand catalogs.
-- vocabulary-storage.toml declares actual field ownership and use sites;
-- every declared token is also present in dagtoml_attribute_value_allowed.
-- ============================================================
INSERT INTO dagtoml_attribute_vocabulary (attribute, applies_to_entity, applies_to_template, ijb_constraint_type, extensible, default_value, layer, backing_check_constraint) VALUES
    ('requirement_kind',  json_array('requirement'),     NULL, 'structural', 1, NULL,   'core', NULL),
    ('test_kind',         json_array('test'),            NULL, 'structural', 1, NULL,   'core', NULL),
    ('priority',          json_array('requirement'),     NULL, 'structural', 0, 'must', 'core', 'priority'),
    ('unit.status',       json_array('unit'),            NULL, 'structural', 0, NULL,   'core', 'unit_status'),
    ('review.status',     json_array('artifact_class'),  json_array('readiness-gate'), 'structural', 0, NULL, 'core', 'review_status'),
    -- Core disclosure-posture vocabularies (spec.md §2.7)
    ('confidentiality',                  NULL, NULL, 'policy', 0, NULL, 'core', NULL),
    ('license',                          NULL, NULL, 'policy', 1, NULL, 'core', NULL),
    ('framework_profile_namespace',      NULL, NULL, 'policy', 0, NULL, 'core', NULL),
    ('provenance.encryption.hash_is_over', NULL, NULL, 'structural', 0, NULL, 'core', NULL),
    ('closure_root.digest_algorithm',      NULL, NULL, 'structural', 1, NULL, 'core', NULL),
    ('trigger_kind',                json_array('rollback_trigger'), NULL, 'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('likelihood',                  json_array('threat'),           NULL, 'structural', 0, NULL, 'profile:agent-assurance', 'likelihood'),
    ('impact',                      json_array('threat'),           NULL, 'structural', 0, NULL, 'profile:agent-assurance', 'impact'),
    ('residual_risk',               json_array('threat'),           NULL, 'structural', 0, NULL, 'profile:agent-assurance', 'residual'),
    ('smoke.decision',              NULL, json_array('smoke-validation'), 'structural', 0, NULL, 'profile:agent-assurance', NULL),
    ('status',                      json_array('smoke_check'),      NULL, 'structural', 0, NULL, 'profile:agent-assurance', 'smoke_status'),
    ('runtime_kind',                NULL, json_array('adapter-contract'), 'structural', 0, NULL, 'profile:agent-assurance', 'runtime_document_runtime_kind_values'),
    ('runtime_network_policy',      NULL, json_array('adapter-contract'), 'structural', 0, NULL, 'profile:agent-assurance', 'runtime_document_runtime_network_policy_values'),
    ('runtime_clock_policy',        NULL, json_array('adapter-contract'), 'structural', 0, NULL, 'profile:agent-assurance', 'runtime_document_runtime_clock_policy_values'),
    ('input_hash_method',           NULL, json_array('adapter-contract'), 'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('adapter_id_derivation',       NULL, json_array('adapter-contract'), 'structural', 0, NULL, 'profile:agent-assurance', 'runtime_document_adapter_id_derivation_values'),
    ('gate_decision_verdict',       NULL, json_array('gate-decision'),    'structural', 0, NULL, 'profile:agent-assurance', 'runtime_document_gate_decision_verdict_values'),
    ('severity_tier',               NULL, json_array('gate-decision'),    'structural', 0, NULL, 'profile:agent-assurance', NULL),
    ('override_decision_method',    NULL, json_array('gate-decision'),    'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('override_rule_operator',      NULL, json_array('gate-decision'),    'structural', 0, NULL, 'profile:agent-assurance', NULL),
    ('evidence_root_algorithm',     NULL, json_array('gate-decision'),    'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('signer_class',                NULL, json_array('gate-decision'),    'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('authority_role',              NULL, json_array('gate-decision'),    'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('autonomy_tier',               NULL, json_array('gate-decision'),    'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('record_signature_algorithm',  NULL, json_array('assertion-log-record'), 'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('record_hash_algorithm',       NULL, json_array('assertion-log-record'), 'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('record_canonical_form',       NULL, json_array('assertion-log-record'), 'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('registry_scheme',             NULL, json_array('adapter-registry-binding'), 'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('adapter_ref_syntax',          NULL, json_array('adapter-registry-binding'), 'structural', 0, NULL, 'profile:agent-assurance', 'runtime_document_adapter_ref_syntax_values'),
    -- Profile: disclosure (4)
    ('disclosure_posture',          json_array('disclosure_attestation'),     NULL, 'policy', 0, NULL, 'profile:disclosure', NULL),
    ('redaction_method',            json_array('redaction'),                  NULL, 'structural', 1, NULL, 'profile:disclosure', NULL),
    ('redaction_reason',            json_array('redaction'),                  NULL, 'policy', 1, NULL, 'profile:disclosure', NULL),
    ('proof_scheme',                json_array('selective_disclosure_proof'), NULL, 'structural', 1, NULL, 'profile:disclosure', NULL),
    ('decider_class',               json_array('cost_record'),                NULL, 'structural', 0, NULL, 'profile:cost',       NULL),
    ('cost_dimension_category',     json_array('cost_record'),                NULL, 'structural', 0, NULL, 'profile:cost',       NULL),
    ('cost_citing_kind',            json_array('cost_record'),                NULL, 'structural', 0, NULL, 'profile:cost',       NULL),
    ('capability_envelope.domain',  NULL, NULL, 'structural', 0, NULL, 'core', NULL),
    ('abstraction_class.id_pattern', NULL, NULL, 'structural', 0, NULL, 'core', NULL),
    ('subject_class',       NULL, json_array('gate-decision'), 'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('provider_id',         NULL, json_array('gate-decision'), 'structural', 1, NULL, 'profile:agent-assurance', NULL),
    ('model_family_id',     NULL, json_array('gate-decision'), 'structural', 1, NULL, 'profile:agent-assurance', NULL),
    -- Profile: com.verivus.runtime (4) — api-snapshot closed witness vocabularies,
    -- and the state-mutation execution-proof vocabularies. RKM06 constrains which
    -- finality_basis each execution_proof_scheme may claim; that pairing is a kind
    -- invariant, not a column constraint, so it is not representable here.
    ('witness_scheme',        NULL, json_array('api-snapshot'), 'structural', 0, NULL, 'profile:com.verivus.runtime', NULL),
    ('attester_observed',     NULL, json_array('api-snapshot'), 'structural', 0, NULL, 'profile:com.verivus.runtime', NULL),
    ('execution_proof_scheme', NULL, json_array('state-mutation'), 'structural', 0, NULL, 'profile:com.verivus.runtime', NULL),
    ('finality_basis',        NULL, json_array('state-mutation'), 'structural', 0, NULL, 'profile:com.verivus.runtime', NULL);

-- attribute_value_allowed: 216 rows, same content as the PG seed.
-- BEGIN GENERATED DECLARED VOCABULARY VALUES
-- Complete catalog: 216 declared pairs, including native-backed tokens.
INSERT INTO dagtoml_attribute_value_allowed (attribute, value) VALUES
    ('abstraction_class.id_pattern', '<slug>.v<integer>'),
    ('adapter_id_derivation', 'content-hash'),
    ('adapter_id_derivation', 'external'),
    ('adapter_id_derivation', 'nonce'),
    ('adapter_ref_syntax', 'content-hash'),
    ('adapter_ref_syntax', 'name-version-pin'),
    ('attester_observed', 'both'),
    ('attester_observed', 'request'),
    ('attester_observed', 'response'),
    ('authority_role', 'auditor'),
    ('authority_role', 'author'),
    ('authority_role', 'peer'),
    ('authority_role', 'release-captain'),
    ('authority_role', 'security-officer'),
    ('authority_role', 'team-lead'),
    ('autonomy_tier', 't0'),
    ('autonomy_tier', 't1'),
    ('autonomy_tier', 't2'),
    ('autonomy_tier', 't3'),
    ('capability_envelope.domain', 'clocks'),
    ('capability_envelope.domain', 'crypto_keys'),
    ('capability_envelope.domain', 'environment'),
    ('capability_envelope.domain', 'filesystem'),
    ('capability_envelope.domain', 'http'),
    ('capability_envelope.domain', 'ipc'),
    ('capability_envelope.domain', 'process_spawn'),
    ('capability_envelope.domain', 'random'),
    ('capability_envelope.domain', 'sockets'),
    ('closure_root.digest_algorithm', 'sha256'),
    ('closure_root.digest_algorithm', 'sha384'),
    ('closure_root.digest_algorithm', 'sha512'),
    ('confidentiality', 'confidential'),
    ('confidentiality', 'embargoed'),
    ('confidentiality', 'public'),
    ('confidentiality', 'restricted'),
    ('confidentiality', 'trade-secret'),
    ('cost_citing_kind', 'assertion-bundle'),
    ('cost_citing_kind', 'evidence-matrix'),
    ('cost_citing_kind', 'gate-decision'),
    ('cost_citing_kind', 'other'),
    ('cost_citing_kind', 'rollback-plan'),
    ('cost_citing_kind', 'smoke-validation'),
    ('cost_citing_kind', 'threat-model'),
    ('cost_dimension_category', 'bandwidth_bytes'),
    ('cost_dimension_category', 'compute_time_seconds'),
    ('cost_dimension_category', 'energy_equivalent'),
    ('cost_dimension_category', 'evidence_run_count'),
    ('cost_dimension_category', 'human_review_time_seconds'),
    ('cost_dimension_category', 'storage_bytes'),
    ('cost_dimension_category', 'token_equivalent'),
    ('decider_class', 'deterministic_check'),
    ('decider_class', 'human_reviewer'),
    ('decider_class', 'llm_consensus'),
    ('decider_class', 'llm_single'),
    ('decider_class', 'notarisation'),
    ('decider_class', 'other'),
    ('decider_class', 'tee_attested_compute'),
    ('decider_class', 'transparency_log_write'),
    ('disclosure_posture', 'embargoed'),
    ('disclosure_posture', 'full'),
    ('disclosure_posture', 'partial'),
    ('disclosure_posture', 'withheld'),
    ('evidence_root_algorithm', 'sha256-merkle-index-order'),
    ('evidence_root_algorithm', 'sha256-merkle-sorted-leaves'),
    ('execution_proof_scheme', 'ledger-transaction'),
    ('execution_proof_scheme', 'provider-receipt'),
    ('execution_proof_scheme', 'tee-quote'),
    ('execution_proof_scheme', 'zk-receipt'),
    ('finality_basis', 'ledger-confirmed'),
    ('finality_basis', 'ledger-final'),
    ('finality_basis', 'none'),
    ('finality_basis', 'provider-acknowledged'),
    ('framework_profile_namespace', 'reverse-dns'),
    ('framework_profile_namespace', 'spec-reserved'),
    ('gate_decision_verdict', 'fail'),
    ('gate_decision_verdict', 'pass'),
    ('impact', 'critical'),
    ('impact', 'high'),
    ('impact', 'low'),
    ('impact', 'medium'),
    ('impact', 'negligible'),
    ('input_hash_method', 'sha256-bytes'),
    ('input_hash_method', 'sha256-cbor-deterministic'),
    ('input_hash_method', 'sha256-jcs'),
    ('likelihood', 'critical'),
    ('likelihood', 'high'),
    ('likelihood', 'low'),
    ('likelihood', 'medium'),
    ('likelihood', 'negligible'),
    ('model_family_id', 'claude'),
    ('model_family_id', 'deepseek'),
    ('model_family_id', 'gemini'),
    ('model_family_id', 'gpt'),
    ('model_family_id', 'grok'),
    ('model_family_id', 'human'),
    ('model_family_id', 'llama'),
    ('model_family_id', 'mistral'),
    ('model_family_id', 'other'),
    ('model_family_id', 'qwen'),
    ('override_decision_method', 'co-signed-human-ai'),
    ('override_decision_method', 'm-of-n'),
    ('override_decision_method', 'single-signer'),
    ('override_rule_operator', '!='),
    ('override_rule_operator', '<'),
    ('override_rule_operator', '<='),
    ('override_rule_operator', '='),
    ('override_rule_operator', '>'),
    ('override_rule_operator', '>='),
    ('override_rule_operator', 'AND'),
    ('override_rule_operator', 'IN'),
    ('override_rule_operator', 'OR'),
    ('priority', 'could'),
    ('priority', 'must'),
    ('priority', 'should'),
    ('proof_scheme', 'blob-commitment-substitution'),
    ('proof_scheme', 'field-commitment-omission'),
    ('proof_scheme', 'merkle-leaf-omission'),
    ('provenance.encryption.hash_is_over', 'ciphertext'),
    ('provenance.encryption.hash_is_over', 'plaintext'),
    ('provider_id', 'anthropic'),
    ('provider_id', 'deepseek'),
    ('provider_id', 'google'),
    ('provider_id', 'human'),
    ('provider_id', 'meta'),
    ('provider_id', 'mistralai'),
    ('provider_id', 'openai'),
    ('provider_id', 'other'),
    ('provider_id', 'qwen'),
    ('provider_id', 'xai'),
    ('record_canonical_form', 'deterministic-cbor'),
    ('record_canonical_form', 'rfc8785-jcs'),
    ('record_hash_algorithm', 'sha256'),
    ('record_signature_algorithm', 'ecdsa-p256'),
    ('record_signature_algorithm', 'ed25519'),
    ('redaction_method', 'blob-replace'),
    ('redaction_method', 'byte-range-delete'),
    ('redaction_method', 'field-path-delete'),
    ('redaction_method', 'field-path-mask'),
    ('redaction_reason', 'license-restricted'),
    ('redaction_reason', 'other'),
    ('redaction_reason', 'pii'),
    ('redaction_reason', 'regulatory'),
    ('redaction_reason', 'secret'),
    ('redaction_reason', 'third-party'),
    ('redaction_reason', 'trade-secret'),
    ('registry_scheme', 'file'),
    ('registry_scheme', 'https'),
    ('registry_scheme', 'ipfs'),
    ('registry_scheme', 'oci'),
    ('requirement_kind', 'correctness'),
    ('requirement_kind', 'functional'),
    ('requirement_kind', 'interface'),
    ('requirement_kind', 'non_functional'),
    ('requirement_kind', 'operational'),
    ('requirement_kind', 'performance'),
    ('requirement_kind', 'policy'),
    ('residual_risk', 'accepted'),
    ('residual_risk', 'mitigated'),
    ('residual_risk', 'open'),
    ('review.status', 'blocked'),
    ('review.status', 'draft'),
    ('review.status', 'in_review'),
    ('review.status', 'ready'),
    ('review.status', 'rereview_needed'),
    ('runtime_clock_policy', 'host-wall-clock'),
    ('runtime_clock_policy', 'injected'),
    ('runtime_clock_policy', 'monotonic-from-zero'),
    ('runtime_clock_policy', 'source-date-epoch'),
    ('runtime_kind', 'oci-action'),
    ('runtime_kind', 'os-sandbox'),
    ('runtime_kind', 'wasi-component'),
    ('runtime_network_policy', 'allowlist'),
    ('runtime_network_policy', 'denied'),
    ('runtime_network_policy', 'loopback-only'),
    ('runtime_network_policy', 'open'),
    ('severity_tier', 'critical'),
    ('severity_tier', 'high'),
    ('severity_tier', 'info'),
    ('severity_tier', 'low'),
    ('severity_tier', 'medium'),
    ('signer_class', 'ai_agent'),
    ('signer_class', 'human'),
    ('signer_class', 'service'),
    ('smoke.decision', 'fail'),
    ('smoke.decision', 'inconclusive'),
    ('smoke.decision', 'pass'),
    ('status', 'fail'),
    ('status', 'inconclusive'),
    ('status', 'pass'),
    ('subject_class', 'downstream-change'),
    ('subject_class', 'self-modification'),
    ('test_kind', 'audit'),
    ('test_kind', 'benchmark'),
    ('test_kind', 'e2e'),
    ('test_kind', 'integration'),
    ('test_kind', 'property'),
    ('test_kind', 'robustness'),
    ('test_kind', 'unit'),
    ('trigger_kind', 'behavioral_anomaly_detected'),
    ('trigger_kind', 'data_corruption'),
    ('trigger_kind', 'determinism_regression'),
    ('trigger_kind', 'error_rate_threshold'),
    ('trigger_kind', 'manual_override'),
    ('trigger_kind', 'memory_safety_regression'),
    ('trigger_kind', 'missing_evidence'),
    ('trigger_kind', 'perf_regression'),
    ('trigger_kind', 'validator_failure'),
    ('trigger_kind', 'windows_ci_regression'),
    ('unit.status', 'blocked'),
    ('unit.status', 'deferred'),
    ('unit.status', 'done'),
    ('unit.status', 'in_progress'),
    ('unit.status', 'pending'),
    ('witness_scheme', 'provider-signature'),
    ('witness_scheme', 'tee-quote'),
    ('witness_scheme', 'tls-notary');
-- END GENERATED DECLARED VOCABULARY VALUES
