-- DAG-TOML reference DuckDB seed (non-normative).
--
-- Mirrors reference/database/postgres/seed.sql, adapted to DuckDB.
-- DuckDB arrays use the LIST syntax `['a','b']` (or `list_value('a','b')`)
-- instead of PG's `ARRAY['a','b']` form.
--
-- Counts (CI-gated by validators/check_attribute_values.py):
--   23 kind_descriptor / 27 entity_kind_descriptor / 31 relation_descriptor /
--   50 attribute_vocabulary / 152 attribute_value_allowed

SET search_path = dagtoml;

-- kind_descriptor (23; +1 cost-record, +3 com.verivus.runtime)
INSERT INTO dagtoml.kind_descriptor (template_kind, layer, descriptor_path, requires_profile) VALUES
    ('kind-descriptor',           'core', 'spec.md',                                                       NULL),
    ('implementation-dag',        'core', 'core/implementation-dag-kind.toml',                             NULL),
    ('traceability',              'core', 'core/traceability-kind.toml',                                   NULL),
    ('readiness-gate',            'core', 'core/readiness-gate-kind.toml',                                 NULL),
    ('contract-declaration',      'core', 'core/contract-declaration-kind.toml',                           NULL),
    ('evidence-matrix',           'core', 'core/evidence-matrix-kind.toml',                                NULL),
    ('profile-descriptor',        'core', 'core/profile-descriptor-kind.toml',                             NULL),
    ('spec-contract',             'profile:agent-assurance', 'profiles/agent-assurance/spec-contract-kind.toml',             'agent-assurance'),
    ('threat-model',              'profile:agent-assurance', 'profiles/agent-assurance/threat-model-kind.toml',              'agent-assurance'),
    ('smoke-validation',          'profile:agent-assurance', 'profiles/agent-assurance/smoke-validation-kind.toml',          'agent-assurance'),
    ('rollback-plan',             'profile:agent-assurance', 'profiles/agent-assurance/rollback-plan-kind.toml',             'agent-assurance'),
    ('adapter-contract',          'profile:agent-assurance', 'profiles/agent-assurance/adapter-contract-kind.toml',          'agent-assurance'),
    ('adapter-registry-binding',  'profile:agent-assurance', 'profiles/agent-assurance/adapter-registry-binding-kind.toml',  'agent-assurance'),
    ('assertion-bundle',          'profile:agent-assurance', 'profiles/agent-assurance/assertion-bundle-kind.toml',          'agent-assurance'),
    ('assertion-log-record',      'profile:agent-assurance', 'profiles/agent-assurance/assertion-log-record-kind.toml',      'agent-assurance'),
    ('gate-decision',             'profile:agent-assurance', 'profiles/agent-assurance/gate-decision-kind.toml',             'agent-assurance'),
    ('disclosure-attestation',    'profile:disclosure',      'profiles/disclosure/disclosure-attestation-kind.toml',         'disclosure'),
    ('redaction-manifest',        'profile:disclosure',      'profiles/disclosure/redaction-manifest-kind.toml',             'disclosure'),
    ('selective-disclosure-proof','profile:disclosure',      'profiles/disclosure/selective-disclosure-proof-kind.toml',     'disclosure'),
    ('cost-record',               'profile:cost',            'profiles/cost/cost-record-kind.toml',                          'cost'),
    ('api-snapshot',              'profile:com.verivus.runtime', 'profiles/com.verivus.runtime/api-snapshot-kind.toml',       'com.verivus.runtime'),
    ('state-mutation',            'profile:com.verivus.runtime', 'profiles/com.verivus.runtime/state-mutation-kind.toml',     'com.verivus.runtime'),
    ('mutation-claim',            'profile:com.verivus.runtime', 'profiles/com.verivus.runtime/mutation-claim-kind.toml',     'com.verivus.runtime');

-- entity_kind_descriptor (27; +1 cost = COST)
INSERT INTO dagtoml.entity_kind_descriptor (entity_kind, id_prefix_pattern, layer, defining_kind, ijb_primitive, ijb_class, description) VALUES
    ('intent',           'INT',           'core', 'traceability',         'thing', 'structural', 'User/business intent; top of trace.'),
    ('feature',          'FEAT',          'core', 'traceability',         'thing', 'structural', 'User-visible capability.'),
    ('requirement',      'REQ',           'core', 'traceability',         'thing', 'structural', 'Normative, testable requirement.'),
    ('regulation',       'REG',           'core', 'traceability',         'thing', 'structural', 'Legal/policy/regulatory obligation.'),
    ('decision',         'DEC',           'core', 'traceability',         'thing', 'structural', 'Design or policy decision.'),
    ('implementation',   'IMP',           'core', 'traceability',         'thing', 'structural', 'Implementation work package.'),
    ('code',             'CODE',          'core', 'traceability',         'thing', 'structural', 'Concrete code artifact.'),
    ('test',             'TEST',          'core', 'traceability',         'thing', 'structural', 'Verification artifact.'),
    ('output',           'OUT',           'core', 'traceability',         'thing', 'structural', 'User-visible output or deliverable.'),
    ('unit',             'U\d+[a-z]?',    'core', 'implementation-dag',   'thing', 'structural', 'DAG unit (regex-keyed).'),
    ('artifact',         'ART',           'core', 'implementation-dag',   'thing', 'structural', 'Internal artifact flowing between DAG units.'),
    ('artifact_class',   'A\d+',          'core', 'readiness-gate',       'thing', 'structural', 'Review artifact class.'),
    ('gate',             'G\d+',          'core', 'readiness-gate',       'thing', 'structural', 'Readiness gate keyed to artifact class.'),
    ('contract',         'C\d+',          'core', 'contract-declaration', 'thing', 'structural', 'Declared contract.'),
    ('claim',            'E\d+',          'core', 'evidence-matrix',      'thing', 'structural', 'Strong claim.'),
    ('evidence',         'EV\d+',         'core', 'evidence-matrix',      'thing', 'structural', 'Proof artifact.'),
    ('matrix',           'M\d+',          'core', 'evidence-matrix',      'thing', 'structural', 'Claim↔evidence linkage.'),
    ('guarantee',        'GUAR',          'profile:agent-assurance', 'spec-contract',  'thing', 'structural', 'Measurable guarantee.'),
    ('invariant',        'INV',           'profile:agent-assurance', 'spec-contract',  'thing', 'structural', 'Invariant the implementation MUST not violate.'),
    ('non_goal',         'NG',            'profile:agent-assurance', 'spec-contract',  'thing', 'structural', 'Explicit non-goal of the change.'),
    ('threat',           'THREAT',        'profile:agent-assurance', 'threat-model',   'thing', 'structural', 'Identified threat to the change/system.'),
    ('smoke_check',      'SMOKE',         'profile:agent-assurance', 'smoke-validation','thing', 'structural', 'Smoke-validation check entry.'),
    ('rollback_trigger', 'TRIG',          'profile:agent-assurance', 'rollback-plan',  'thing', 'structural', 'Pre-declared rollback trigger condition.'),
    -- Profile: disclosure (3)
    ('disclosure_attestation',     'DISC', 'profile:disclosure', 'disclosure-attestation',     'thing', 'structural', 'Signed posture statement that a named subject was disclosed at a given posture.'),
    ('redaction',                  'RED',  'profile:disclosure', 'redaction-manifest',         'thing', 'structural', 'A byte-range or field-path inside a source artifact that was removed before publication.'),
    ('selective_disclosure_proof', 'SDP',  'profile:disclosure', 'selective-disclosure-proof', 'thing', 'structural', 'A commitment a recipient can verify to confirm the publisher knew the omitted content.'),
    ('cost_record',                'COST', 'profile:cost',       'cost-record',                'thing', 'structural', 'Declared cost of one costed action (Stream G Cost-Witnessed Decision).');

-- relation_descriptor (30) — DuckDB arrays use ['a','b'] syntax.
INSERT INTO dagtoml.relation_descriptor (predicate, domain, range, inverse_of, cardinality, is_acyclic, target_freeform, ijb_primitive, ijb_class, layer) VALUES
    ('derived_from',           ['intent'],                       ['intent'],                                       NULL,            NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('realized_by',            ['intent'],                       ['feature','requirement'],                        'realizes',      NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('realizes',               ['feature','code','output'],      ['intent','implementation','requirement','feature'], 'realized_by', NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('constrained_by',         ['feature'],                      ['requirement','regulation'],                     'constrains',    NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('implemented_by',         ['feature'],                      ['implementation'],                               'implements',    NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('produces',               ['feature','unit'],               ['output','artifact'],                            NULL,            NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('constrains',             ['requirement','regulation'],     ['feature','implementation','requirement'],       'constrained_by',NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('verified_by',            ['requirement','regulation'],     ['test'],                                         'verifies',      NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('addresses',              ['decision'],                     ['requirement','regulation'],                     NULL,            NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('shapes',                 ['decision'],                     ['implementation','code'],                        NULL,            NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('supersedes',             ['decision'],                     ['decision'],                                     NULL,            NULL, TRUE,  FALSE, 'path', 'structural', 'core'),
    ('implements',             ['implementation'],               ['feature','requirement'],                        'implemented_by',NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('guided_by',              ['implementation'],               ['decision'],                                     NULL,            NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('code',                   ['implementation'],               ['code'],                                         NULL,            NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('tests',                  ['implementation'],               ['test'],                                         NULL,            NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('downstream_outputs',     ['implementation'],               ['output'],                                       NULL,            NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('verifies',               ['test'],                         ['requirement','regulation'],                     'verified_by',   NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('depends_on',             ['unit'],                         ['unit'],                                         'blocks',        NULL, TRUE,  FALSE, 'path', 'structural', 'core'),
    ('blocks',                 ['unit'],                         ['unit'],                                         'depends_on',    NULL, TRUE,  FALSE, 'path', 'structural', 'core'),
    ('consumes',               ['unit'],                         ['artifact'],                                     NULL,            NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('artifact_class',         ['gate'],                         ['artifact_class'],                               NULL,            1,    FALSE, FALSE, 'path', 'structural', 'core'),
    ('contract:depends_on',    ['contract'],                     ['contract'],                                     NULL,            NULL, TRUE,  FALSE, 'path', 'structural', 'core'),
    ('contract:supersedes',    ['contract'],                     ['contract'],                                     NULL,            NULL, TRUE,  FALSE, 'path', 'structural', 'core'),
    ('related_to',             ['contract'],                     ['contract'],                                     NULL,            NULL, FALSE, FALSE, 'path', 'structural', 'core'),
    ('applies_to',             ['contract'],                     []::VARCHAR[],                                    NULL,            NULL, FALSE, TRUE,  'path', 'structural', 'core'),
    ('contract:verified_by',   ['contract'],                     []::VARCHAR[],                                    NULL,            NULL, FALSE, TRUE,  'path', 'structural', 'core'),
    ('claim',                  ['matrix'],                       ['claim'],                                        NULL,            1,    FALSE, FALSE, 'path', 'structural', 'core'),
    ('claim_id',               ['matrix'],                       ['claim'],                                        NULL,            1,    FALSE, FALSE, 'path', 'structural', 'core'),
    ('evidence',               ['matrix'],                       ['evidence'],                                     NULL,            1,    FALSE, FALSE, 'path', 'structural', 'core'),
    ('evidence_id',            ['matrix'],                       ['evidence'],                                     NULL,            1,    FALSE, FALSE, 'path', 'structural', 'core'),
    -- SPEC §12 closure-root marker — applies to every conforming kind.
    ('cites_upstream',         []::VARCHAR[],                    []::VARCHAR[],                                    NULL,            NULL, TRUE,  TRUE,  'path', 'structural', 'core');

-- relation_descriptor row count is now 31 (one per [[relations]] block in core/ontology.toml).

-- attribute_vocabulary (50 rows; matches postgres/seed.sql vocab set; includes agent-assurance subject_class/provider_id/model_family_id for gate-decision INV06)
INSERT INTO dagtoml.attribute_vocabulary (attribute, applies_to_entity, applies_to_template, ijb_constraint_type, extensible, default_value, layer, backing_enum_type) VALUES
    ('requirement_kind',  ['requirement'],     NULL, 'structural', TRUE,  NULL,  'core', NULL),
    ('test_kind',         ['test'],            NULL, 'structural', TRUE,  NULL,  'core', NULL),
    ('priority',          ['requirement'],     NULL, 'structural', FALSE, 'must','core', 'priority_level'),
    ('unit.status',       ['unit'],            NULL, 'structural', FALSE, NULL,  'core', 'unit_status'),
    ('review.status',     ['artifact_class'],  ['readiness-gate'], 'structural', FALSE, NULL, 'core', 'review_status'),
    -- Core disclosure-posture vocabularies (spec.md §2.7)
    ('confidentiality',                  NULL, NULL, 'policy', FALSE, NULL, 'core', NULL),
    ('license',                          NULL, NULL, 'policy', TRUE,  NULL, 'core', NULL),
    ('framework_profile_namespace',      NULL, NULL, 'structural', FALSE, NULL, 'core', NULL),
    ('provenance.encryption.hash_is_over', NULL, NULL, 'structural', FALSE, NULL, 'core', NULL),
    ('closure_root.digest_algorithm',      NULL, NULL, 'structural', TRUE,  NULL, 'core', NULL),
    ('trigger_kind',                ['rollback_trigger'], NULL, 'structural', TRUE,  NULL, 'profile:agent-assurance', NULL),
    ('likelihood',                  ['threat'],           NULL, 'structural', FALSE, NULL, 'profile:agent-assurance', 'risk_level'),
    ('impact',                      ['threat'],           NULL, 'structural', FALSE, NULL, 'profile:agent-assurance', 'risk_level'),
    ('residual_risk',               ['threat'],           NULL, 'structural', FALSE, NULL, 'profile:agent-assurance', 'residual_risk'),
    ('smoke.decision',              NULL, ['smoke-validation'], 'structural', FALSE, NULL, 'profile:agent-assurance', 'smoke_decision'),
    ('status',                      ['smoke_check'],      NULL, 'structural', FALSE, NULL, 'profile:agent-assurance', 'smoke_decision'),
    ('runtime_kind',                NULL, ['adapter-contract'], 'structural', FALSE, NULL, 'profile:agent-assurance', 'runtime_kind'),
    ('runtime_network_policy',      NULL, ['adapter-contract'], 'structural', FALSE, NULL, 'profile:agent-assurance', 'network_policy'),
    ('runtime_clock_policy',        NULL, ['adapter-contract'], 'structural', FALSE, NULL, 'profile:agent-assurance', 'clock_policy'),
    ('input_hash_method',           NULL, ['adapter-contract'], 'structural', TRUE,  NULL, 'profile:agent-assurance', NULL),
    ('adapter_id_derivation',       NULL, ['adapter-contract'], 'structural', FALSE, NULL, 'profile:agent-assurance', 'adapter_id_derivation'),
    ('gate_decision_verdict',       NULL, ['gate-decision'],    'structural', FALSE, NULL, 'profile:agent-assurance', 'gate_verdict'),
    ('severity_tier',               NULL, ['gate-decision'],    'structural', FALSE, NULL, 'profile:agent-assurance', 'severity_tier'),
    ('override_decision_method',    NULL, ['gate-decision'],    'structural', TRUE,  NULL, 'profile:agent-assurance', NULL),
    ('override_rule_operator',      NULL, ['gate-decision'],    'structural', FALSE, NULL, 'profile:agent-assurance', 'override_rule_op'),
    ('evidence_root_algorithm',     NULL, ['gate-decision'],    'structural', TRUE,  NULL, 'profile:agent-assurance', NULL),
    ('signer_class',                NULL, ['gate-decision'],    'structural', TRUE,  NULL, 'profile:agent-assurance', NULL),
    ('authority_role',              NULL, ['gate-decision'],    'structural', TRUE,  NULL, 'profile:agent-assurance', NULL),
    ('autonomy_tier',               NULL, ['gate-decision'],    'structural', TRUE,  NULL, 'profile:agent-assurance', NULL),
    ('record_signature_algorithm',  NULL, ['assertion-log-record'], 'structural', TRUE, NULL, 'profile:agent-assurance', NULL),
    ('record_hash_algorithm',       NULL, ['assertion-log-record'], 'structural', TRUE, NULL, 'profile:agent-assurance', NULL),
    ('record_canonical_form',       NULL, ['assertion-log-record'], 'structural', TRUE, NULL, 'profile:agent-assurance', NULL),
    ('registry_scheme',             NULL, ['adapter-registry-binding'], 'structural', TRUE, NULL, 'profile:agent-assurance', NULL),
    ('adapter_ref_syntax',          NULL, ['adapter-registry-binding'], 'structural', FALSE, NULL, 'profile:agent-assurance', 'adapter_ref_syntax'),
    -- Profile: disclosure (4)
    ('disclosure_posture',          ['disclosure_attestation'],     NULL, 'structural', FALSE, NULL, 'profile:disclosure', NULL),
    ('redaction_method',            ['redaction'],                  NULL, 'structural', TRUE,  NULL, 'profile:disclosure', NULL),
    ('redaction_reason',            ['redaction'],                  NULL, 'structural', TRUE,  NULL, 'profile:disclosure', NULL),
    ('proof_scheme',                ['selective_disclosure_proof'], NULL, 'structural', TRUE,  NULL, 'profile:disclosure', NULL),
    ('decider_class',               ['cost_record'],                NULL, 'structural', FALSE, NULL, 'profile:cost',       NULL),
    ('cost_dimension_category',     ['cost_record'],                NULL, 'structural', FALSE, NULL, 'profile:cost',       NULL),
    ('cost_citing_kind',            ['cost_record'],                NULL, 'structural', FALSE, NULL, 'profile:cost',       NULL),
    ('capability_envelope.domain',  NULL, NULL, 'structural', FALSE, NULL, 'core', NULL),
    ('abstraction_class.id_pattern', NULL, NULL, 'structural', FALSE, NULL, 'core', NULL),
    ('subject_class',       NULL, ['gate-decision'], 'structural', TRUE, NULL, 'profile:agent-assurance', NULL),
    ('provider_id',         NULL, ['gate-decision'], 'structural', TRUE, NULL, 'profile:agent-assurance', NULL),
    ('model_family_id',     NULL, ['gate-decision'], 'structural', TRUE, NULL, 'profile:agent-assurance', NULL),
    -- Profile: com.verivus.runtime (4) — api-snapshot closed witness vocabularies,
    -- and the state-mutation execution-proof vocabularies. RKM06 constrains which
    -- finality_basis each execution_proof_scheme may claim; that pairing is a kind
    -- invariant, not a column constraint, so it is not representable here.
    ('witness_scheme',        NULL, ['api-snapshot'], 'structural', FALSE, NULL, 'profile:com.verivus.runtime', NULL),
    ('attester_observed',     NULL, ['api-snapshot'], 'structural', FALSE, NULL, 'profile:com.verivus.runtime', NULL),
    ('execution_proof_scheme', NULL, ['state-mutation'], 'structural', FALSE, NULL, 'profile:com.verivus.runtime', NULL),
    ('finality_basis',        NULL, ['state-mutation'], 'structural', FALSE, NULL, 'profile:com.verivus.runtime', NULL);

-- attribute_value_allowed (152), identical to postgres/seed.sql.
INSERT INTO dagtoml.attribute_value_allowed (attribute, value) VALUES
    ('requirement_kind', 'functional'),
    ('requirement_kind', 'non_functional'),
    ('requirement_kind', 'policy'),
    ('requirement_kind', 'interface'),
    ('requirement_kind', 'performance'),
    ('requirement_kind', 'correctness'),
    ('requirement_kind', 'operational'),
    ('test_kind', 'unit'),
    ('test_kind', 'integration'),
    ('test_kind', 'e2e'),
    ('test_kind', 'audit'),
    ('test_kind', 'property'),
    ('test_kind', 'robustness'),
    ('test_kind', 'benchmark'),
    ('trigger_kind', 'error_rate_threshold'),
    ('trigger_kind', 'behavioral_anomaly_detected'),
    ('trigger_kind', 'determinism_regression'),
    ('trigger_kind', 'perf_regression'),
    ('trigger_kind', 'memory_safety_regression'),
    ('trigger_kind', 'data_corruption'),
    ('trigger_kind', 'windows_ci_regression'),
    ('trigger_kind', 'validator_failure'),
    ('trigger_kind', 'missing_evidence'),
    ('trigger_kind', 'manual_override'),
    ('input_hash_method', 'sha256-bytes'),
    ('input_hash_method', 'sha256-jcs'),
    ('input_hash_method', 'sha256-cbor-deterministic'),
    ('override_decision_method', 'single-signer'),
    ('override_decision_method', 'm-of-n'),
    ('override_decision_method', 'co-signed-human-ai'),
    ('evidence_root_algorithm', 'sha256-merkle-sorted-leaves'),
    ('evidence_root_algorithm', 'sha256-merkle-index-order'),
    ('signer_class', 'human'),
    ('signer_class', 'ai_agent'),
    ('signer_class', 'service'),
    ('authority_role', 'author'),
    ('authority_role', 'peer'),
    ('authority_role', 'team-lead'),
    ('authority_role', 'release-captain'),
    ('authority_role', 'security-officer'),
    ('authority_role', 'auditor'),
    ('autonomy_tier', 't0'),
    ('autonomy_tier', 't1'),
    ('autonomy_tier', 't2'),
    ('autonomy_tier', 't3'),
    ('record_signature_algorithm', 'ed25519'),
    ('record_signature_algorithm', 'ecdsa-p256'),
    ('record_hash_algorithm', 'sha256'),
    ('record_canonical_form', 'deterministic-cbor'),
    ('record_canonical_form', 'rfc8785-jcs'),
    ('registry_scheme', 'file'),
    ('registry_scheme', 'https'),
    ('registry_scheme', 'oci'),
    ('registry_scheme', 'ipfs'),
    -- Core disclosure-posture vocab values (spec.md §2.7)
    ('confidentiality', 'public'),
    ('confidentiality', 'restricted'),
    ('confidentiality', 'confidential'),
    ('confidentiality', 'trade-secret'),
    ('confidentiality', 'embargoed'),
    ('framework_profile_namespace', 'spec-reserved'),
    ('framework_profile_namespace', 'reverse-dns'),
    ('provenance.encryption.hash_is_over', 'plaintext'),
    ('provenance.encryption.hash_is_over', 'ciphertext'),
    -- Core closure-root digest algorithms (SPEC §12.1).
    ('closure_root.digest_algorithm', 'sha256'),
    ('closure_root.digest_algorithm', 'sha384'),
    ('closure_root.digest_algorithm', 'sha512'),
    -- Profile: disclosure vocab values
    ('disclosure_posture', 'full'),
    ('disclosure_posture', 'partial'),
    ('disclosure_posture', 'withheld'),
    ('disclosure_posture', 'embargoed'),
    ('redaction_method', 'byte-range-delete'),
    ('redaction_method', 'field-path-delete'),
    ('redaction_method', 'field-path-mask'),
    ('redaction_method', 'blob-replace'),
    ('redaction_reason', 'pii'),
    ('redaction_reason', 'secret'),
    ('redaction_reason', 'trade-secret'),
    ('redaction_reason', 'license-restricted'),
    ('redaction_reason', 'third-party'),
    ('redaction_reason', 'regulatory'),
    ('redaction_reason', 'other'),
    ('proof_scheme', 'merkle-leaf-omission'),
    ('proof_scheme', 'field-commitment-omission'),
    ('proof_scheme', 'blob-commitment-substitution'),
    -- Profile: cost vocab values (Stream G Cost-Witnessed Decision).
    ('decider_class', 'deterministic_check'),
    ('decider_class', 'llm_single'),
    ('decider_class', 'llm_consensus'),
    ('decider_class', 'human_reviewer'),
    ('decider_class', 'tee_attested_compute'),
    ('decider_class', 'notarisation'),
    ('decider_class', 'transparency_log_write'),
    ('decider_class', 'other'),
    ('cost_dimension_category', 'token_equivalent'),
    ('cost_dimension_category', 'compute_time_seconds'),
    ('cost_dimension_category', 'storage_bytes'),
    ('cost_dimension_category', 'bandwidth_bytes'),
    ('cost_dimension_category', 'human_review_time_seconds'),
    ('cost_dimension_category', 'energy_equivalent'),
    ('cost_dimension_category', 'evidence_run_count'),
    ('cost_citing_kind', 'gate-decision'),
    ('cost_citing_kind', 'evidence-matrix'),
    ('cost_citing_kind', 'assertion-bundle'),
    ('cost_citing_kind', 'smoke-validation'),
    ('cost_citing_kind', 'threat-model'),
    ('cost_citing_kind', 'rollback-plan'),
    ('cost_citing_kind', 'other'),
    ('capability_envelope.domain', 'filesystem'),
    ('capability_envelope.domain', 'sockets'),
    ('capability_envelope.domain', 'http'),
    ('capability_envelope.domain', 'clocks'),
    ('capability_envelope.domain', 'random'),
    ('capability_envelope.domain', 'environment'),
    ('capability_envelope.domain', 'process_spawn'),
    ('capability_envelope.domain', 'ipc'),
    ('capability_envelope.domain', 'crypto_keys'),
    ('abstraction_class.id_pattern', '<slug>.v<integer>'),
    ('subject_class', 'downstream-change'),
    ('subject_class', 'self-modification'),
    ('provider_id', 'anthropic'),
    ('provider_id', 'openai'),
    ('provider_id', 'google'),
    ('provider_id', 'xai'),
    ('provider_id', 'mistralai'),
    ('provider_id', 'meta'),
    ('provider_id', 'deepseek'),
    ('provider_id', 'qwen'),
    ('provider_id', 'human'),
    ('provider_id', 'other'),
    ('model_family_id', 'claude'),
    ('model_family_id', 'gpt'),
    ('model_family_id', 'gemini'),
    ('model_family_id', 'grok'),
    ('model_family_id', 'mistral'),
    ('model_family_id', 'llama'),
    ('model_family_id', 'deepseek'),
    ('model_family_id', 'qwen'),
    ('model_family_id', 'human'),
    ('model_family_id', 'other'),
    -- Profile: com.verivus.runtime witness vocabularies (6).
    ('witness_scheme', 'tls-notary'),
    ('witness_scheme', 'provider-signature'),
    ('witness_scheme', 'tee-quote'),
    ('attester_observed', 'request'),
    ('attester_observed', 'response'),
    ('attester_observed', 'both'),
    -- Profile: com.verivus.runtime mutation vocabularies (8). Closed and
    -- non-enum-backed, exactly like the witness pair above, so their values
    -- belong here rather than in a CHECK list.
    ('execution_proof_scheme', 'ledger-transaction'),
    ('execution_proof_scheme', 'provider-receipt'),
    ('execution_proof_scheme', 'tee-quote'),
    ('execution_proof_scheme', 'zk-receipt'),
    ('finality_basis', 'none'),
    ('finality_basis', 'provider-acknowledged'),
    ('finality_basis', 'ledger-confirmed'),
    ('finality_basis', 'ledger-final');
